In [11]:
import numpy as np

`numpy.loadtxt(fname, dtype=, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0)`

`dtype`:数据类型，为int,float等

`comments`:指定文件以什么注释

`delimiter`:指定数据之间以什么符号分割

`skiprows`:跳过前几行

`usecols`:使用指定列

`unpack`:把每一列当成一个向量输出, 而不是合并在一起。

In [12]:
%%writefile test.txt
A B C
1, 2, 3
# AA AAA
4, 5, 6
7, 8, 9

Overwriting test.txt


In [13]:
a = np.loadtxt('test.txt', dtype=int, delimiter=',', skiprows=1, comments='#')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
(a, b) = np.loadtxt('test.txt', dtype=int, skiprows=1, comments='#', delimiter=',', usecols=(0, 2), unpack=True)
print(a, b)

[1 4 7] [3 6 9]


最后介绍converters参数, 这个是对数据进行预处理的参数, 我们可以先定义一个函数， 这里的converters是一个字典, 表示第零列使用函数add_one来进行预处理

In [16]:
def add_one(x):
    return int(x)+1#注意到这里使用的字符的数据结构
    
(a, b) = np.loadtxt('test.txt', dtype=int, skiprows=1, converters={0:add_one}, comments='#', delimiter=',', usecols=(0, 2), unpack=True)
print(a, b)

[2 5 8] [3 6 9]
